export const LOTTERY_ABI = [
  // ── Events ────────────────────────────────────────────────────────────────
  {
    name: "TicketsPurchased",
    type: "event",
    inputs: [
      { name: "player",     type: "address", indexed: true  },
      { name: "numTickets", type: "uint256", indexed: false },
      { name: "poolSize",   type: "uint256", indexed: false },
    ],
  },
  {
    name: "DrawRequested",
    type: "event",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "lotteryId", type: "uint256", indexed: true },
    ],
  },
  {
    name: "WinnerPicked",
    type: "event",
    inputs: [
      { name: "lotteryId", type: "uint256", indexed: true  },
      { name: "winner",    type: "address", indexed: true  },
      { name: "prize",     type: "uint256", indexed: false },
      { name: "fee",       type: "uint256", indexed: false },
    ],
  },
  {
    name: "LotteryReset",
    type: "event",
    inputs: [{ name: "newLotteryId", type: "uint256", indexed: true }],
  },
  // ── Write functions ───────────────────────────────────────────────────────
  {
    name: "buyTickets",
    type: "function",
    stateMutability: "payable",
    inputs:  [{ name: "numberOfTickets", type: "uint256" }],
    outputs: [],
  },
  {
    name: "requestDraw",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [],
    outputs: [],
  },
  {
    name: "withdrawFees",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [],
    outputs: [],
  },
  {
    name: "pause",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [],
    outputs: [],
  },
  {
    name: "unpause",
    type: "function",
    stateMutability: "nonpayable",
    inputs:  [],
    outputs: [],
  },
  // ── View functions ────────────────────────────────────────────────────────
  {
    name: "getLotteryState",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    name: "getPrizePool",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getTicketEntries",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    name: "getUniquePlayers",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    name: "getPlayerTickets",
    type: "function",
    stateMutability: "view",
    inputs:  [{ name: "p", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getDrawHistory",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "lotteryId",     type: "uint256" },
          { name: "winner",        type: "address" },
          { name: "prize",         type: "uint256" },
          { name: "timestamp",     type: "uint256" },
          { name: "uniquePlayers", type: "uint256" },
          { name: "totalTickets",  type: "uint256" },
        ],
      },
    ],
  },
  {
    name: "getDrawHistoryCount",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getAccumulatedFees",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getConfig",
    type: "function",
    stateMutability: "pure",
    inputs:  [],
    outputs: [
      { name: "ticketPrice",          type: "uint256" },
      { name: "maxTicketsPerPlayer",   type: "uint256" },
      { name: "prizePercentage",       type: "uint256" },
      { name: "feePercentage",         type: "uint256" },
    ],
  },
  {
    name: "owner",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "paused",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "s_lotteryId",
    type: "function",
    stateMutability: "view",
    inputs:  [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
